FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
ENV NEXT_FONT_GOOGLE_DISABLE_DOWNLOADS=true
RUN pnpm build

EXPOSE 3001
CMD ["pnpm", "exec", "next", "start", "-p", "3001", "-H", "0.0.0.0"]